# Generated by Django 4.1.3 on 2022-12-03 21:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tree", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Название отдела"),
        ),
        migrations.AlterField(
            model_name="department",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="tree.department",
                verbose_name="отдел-родитель",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="tree.department",
                verbose_name="отдел",
            ),
        ),
    ]
