# Generated by Django 4.1.3 on 2022-12-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tree",
            "0002_alter_department_name_alter_department_parent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="level",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="lft",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="rght",
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="department",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
